version: "3"

services:
  verifier:
    image: ethereumoptimism/go-ethereum:latest
    volumes:
      - verifier:/root/.ethereum:rw
    env_file:
      - docker-compose.env
    environment:
      - ROLLUP_VERIFIER_ENABLE=true
      - CHAIN_ID=9000
      - NETWORK_ID=9000
      - DEV=true
      - DATADIR=/root/.ethereum
      - RPC_ENABLE=true
      - RPC_ADDR=verifier
      - RPC_CORS_DOMAIN=*
      - RPC_VHOSTS=*
      - RPC_PORT=8045
      - WS=true
      - WS_ADDR=0.0.0.0
      - WS_PORT=8046
      - IPC_DISABLE=true
      - RPC_API=eth,net,rollup,web3
      - WS_API=eth,net,rollup,web3
      - WS_ORIGINS=*
      - GASPRICE=0
      - NO_USB=true
      - GCMODE=archive
      - NO_DISCOVER=true
      - USING_OVM=true
      - ETH1_SYNC_SERVICE_ENABLE=true
      - ETH1_CONFIRMATION_DEPTH=10
      - ETH1_CHAINID=5
      - ETH1_NETWORKID=5
      - ETH1_CTC_DEPLOYMENT_HEIGHT=4049579
      - ETH1_ADDRESS_RESOLVER_ADDRESS=0xf8288f17B625041b8ada6A2434ece72328225dcc
      - TARGET_GAS_LIMIT=9000000
      - ETH1_L1_CROSS_DOMAIN_MESSENGER_ADDRESS=0x9c4D992cAEC010F1018EbF5C2f10277f44F80b53
      - ROLLUP_ADDRESS_MANAGER_OWNER_ADDRESS=0x4107438C1b1579f258AF9d1AC06194C4a0F55040
      - ROLLUP_STATE_DUMP_PATH=https://raw.githubusercontent.com/jchancehud/optimism-info/master/state-dump.latest.json
      - ROLLUP_DIFFDB_CACHE=1
    ports:
      - 8045:8045
      - 8046:8046

  fraud_prover:
    image: ethereumoptimism/fraud-prover:latest
    env_file:
      - docker-compose.env
    environment:
      - NO_TIMEOUT=true
      - L2_NODE_WEB3_URL=http://verifier:8045
      - L1_START_OFFSET=4049579
      - POLLING_INTERVAL=5000
      - RUN_GAS_LIMIT=8999999
      - RELAY_GAS_LIMIT=8999999
      - FROM_L2_TRANSACTION_INDEX=1
      - L2_BLOCK_OFFSET=1

volumes:
  verifier:
