version: "3"

services:
  verifier:
    image: ethereumoptimism/go-ethereum:latest
    volumes:
      - verifier:/root/.ethereum:rw
    env_file:
      - docker-compose.env
    environment:
      - ROLLUP_VERIFIER_ENABLE=true
      - CHAIN_ID=69
      - NETWORK_ID=69
      - DEV=true
      - DATADIR=/root/.ethereum
      - RPC_ENABLE=true
      - RPC_ADDR=verifier
      - RPC_CORS_DOMAIN=*
      - RPC_VHOSTS=*
      - RPC_PORT=8045
      - WS=true
      - WS_ADDR=0.0.0.0
      - WS_PORT=8046
      - IPC_DISABLE=true
      - RPC_API=eth,net,rollup,web3
      - WS_API=eth,net,rollup,web3
      - WS_ORIGINS=*
      - GASPRICE=0
      - NO_USB=true
      - GCMODE=archive
      - NO_DISCOVER=true
      - USING_OVM=true
      - ETH1_SYNC_SERVICE_ENABLE=true
      - ETH1_CONFIRMATION_DEPTH=0
      - ETH1_CHAINID=42
      - ETH1_NETWORKID=42
      - ETH1_CTC_DEPLOYMENT_HEIGHT=22544064
      - ETH1_ADDRESS_RESOLVER_ADDRESS=0xDDBfB20007D0dC444Cfe0dd0085BE10D6B63A650
      - ROLLUP_ADDRESS_MANAGER_OWNER_ADDRESS=0x4107438C1b1579f258AF9d1AC06194C4a0F55040
      - TARGET_GAS_LIMIT=9000000
      - ETH_L1_CROSS_DOMAIN_MESSENGER_ADDRESS=0xee2BD26f8F3C8Ab1c85D191231040E179901591a
      - ROLLUP_STATE_DUMP_PATH=https://raw.githubusercontent.com/ethereum-optimism/regenesis/master/kovan/1.json
    ports:
      - 8045:8045
      - 8046:8046

  fraud_prover:
    image: ethereumoptimism/fraud-prover:latest
    env_file:
      - docker-compose.env
    environment:
      - NO_TIMEOUT=true
      - L2_NODE_WEB3_URL=http://verifier:8045
      - L1_START_OFFSET=22544064
      - POLLING_INTERVAL=5000
      - RUN_GAS_LIMIT=9500000
      - FROM_L2_TRANSACTION_INDEX=1
      - L2_BLOCK_OFFSET=1

volumes:
  verifier:
